# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
cache: packages

before_install:
  - sudo apt-get -y install libudunits2-dev
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install gdal-bin libgdal-dev #libhdf5-7
  - sudo apt-get install -f
  - gdal-config --version


after_success:
  - Rscript -e 'covr::codecov()'
